<h1>nested_ptr (C++11)</h1>
<p><pre class="codehilite"><code class="language-cpp"><a href="http://cpprefjp.github.io/reference/exception/exception_ptr.html">exception_ptr</a> nested_ptr() const noexcept;<span style="color: #000"></span></code></pre>
</p>
<h2>概要</h2>
<p>入れ子になった例外へのポインタを取得する</p>
<h2>戻り値</h2>
<p>メンバとして保持している、入れ子になった例外へのポインタを返す。</p>
<h2>例外</h2>
<p>投げない</p>
<h2>例</h2>
<p><pre class="codehilite"><code class="language-cpp"><span style="color:#ff0000">nested_ptr</span>());
    }
  }
  catch (int&amp; x) {
    std::cout &lt;&lt; "3rd caught: " &lt;&lt; x &lt;&lt; std::endl;
  }
}<span style="color: #000">#include &lt;exception&gt;
#include &lt;iostream&gt;

class my_exception : public std::nested_exception {};

int main()
{
  try {
    try {
      try {
        throw 1; // int値を送出
      }
      catch (int&amp; x) {
        std::cout &lt;&lt; "1st caught: " &lt;&lt; x &lt;&lt; std::endl;
        throw my_exception(); // 現在の例外(int)を入れ子にしてmy_exceptionを送出
      }
    }
    catch (my_exception&amp; e) {
      std::cout &lt;&lt; "2nd caught: my_exception(nested_exception)." &lt;&lt; std::endl;
      // 入れ子になっている例外(int)を送出
      std::rethrow_exception(e.</span></code></pre>
</p>
<h3>出力</h3>
<p><pre><code><span style="color: #000">1st caught: 1
2nd caught: my_exception(nested_exception).
3rd caught: 1
</span></code></pre></p>
<h2>バージョン</h2>
<h3>言語</h3>
<ul>
<li>C++11</li>
</ul>
<h3>処理系</h3>
<ul>
<li><a href="http://cpprefjp.github.io/implementation.html#clang">Clang</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC</a>: </li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC, C++0x mode</a>: 4.7.0</li>
<li><a href="http://cpprefjp.github.io/implementation.html#icc">ICC</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#visual_cpp">Visual C++</a> ??</li>
</ul>
<h2>参照</h2>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/exception/nested_exception/nested_ptr.md" target="_blank">編集</a></footer>