<h1>rethrow_if_nested (C++11)</h1>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">namespace std {
  template &lt;class E&gt;
  void rethrow_if_nested(const E&amp; e);
}</span></code></pre>
</p>
<h2>概要</h2>
<p>入れ子になった例外が存在する場合に、入れ子になった例外を送出する</p>
<h2>効果</h2>
<p>型<code><span style="color: #000">E</span></code>が<a href="http://cpprefjp.github.io/reference/exception/nested_exception.html"><code><span style="color: #000">nested_exception</span></code></a>を継承した型だった場合、
<code><span style="color: #000">dynamic_cast&lt;const</span></code><a href="http://cpprefjp.github.io/reference/exception/nested_exception.html"><code><span style="color: #000">nested_exception</span></code></a><code><span style="color: #000">&amp;&gt;(e).</span></code><a href="http://cpprefjp.github.io/reference/exception/nested_exception/rethrow_nested.html"><code><span style="color: #000">rethrow_nested</span></code></a><code><span style="color: #000">()</span></code>を行う。そうでなければ何もしない。</p>
<h2>戻り値</h2>
<p>なし</p>
<h2>例</h2>
<p><pre class="codehilite"><code class="language-cpp"><span style="color:#ff0000">nested_exception </span>{};

// 現在の例外を取得
template &lt;class T&gt;
std::shared_ptr&lt;T&gt; get_exception(std::exception_ptr ep)
{
  try {
    std::rethrow_exception(ep);
  }
  catch (T&amp; e) {
    return std::shared_ptr&lt;T&gt;(new T(e));
  }
  catch (...) {}
  return nullptr;
}

// 入れ子になってる例外を取得
template &lt;class T&gt;
std::shared_ptr&lt;T&gt; get_nested_exception(std::nested_exception&amp; ex)
{
  try {
    std::<span style="color:#ff0000">rethrow_if_nested</span>(ex); // 入れ子になってる例外を送出
  }
  catch (T&amp; e) {
    return std::shared_ptr&lt;T&gt;(new T(e));
  }
  catch (...) {}
  return nullptr;
}

int main()
{
  try {
    try {
      throw inner_error();
    }
    catch (...) {
      // inner_errorを入れ子にしてouter_errorを送出
      std::<span style="color:#ff0000">throw_with_nested</span>(outer_error());
    }
  }
  catch (...) {
    // 外側の例外を取得
    if (std::shared_ptr&lt;outer_error&gt; outer = get_exception&lt;outer_error&gt;(std::current_exception())) {
      std::cout &lt;&lt; "outer" &lt;&lt; std::endl;

      // 入れ子になった例外を取得
      if (std::shared_ptr&lt;inner_error&gt; inner = get_nested_exception&lt;inner_error&gt;(*outer)) {
        std::cout &lt;&lt; "inner" &lt;&lt; std::endl;
      }
    }
  }
}<span style="color: #000">#include &lt;iostream&gt;
#include &lt;exception&gt;
#include &lt;memory&gt;

struct inner_error : public std::exception {};
struct outer_error : public std::</span></code></pre>
</p>
<h3>出力</h3>
<p><pre><code><span style="color: #000">outer
inner
</span></code></pre></p>
<h2>バージョン</h2>
<h3>言語</h3>
<ul>
<li>C++11</li>
</ul>
<h3>処理系</h3>
<ul>
<li><a href="http://cpprefjp.github.io/implementation.html#clang">Clang</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC</a>: </li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC, C++0x mode</a>: 4.7.0</li>
<li><a href="http://cpprefjp.github.io/implementation.html#icc">ICC</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#visual_cpp">Visual C++</a> ??</li>
</ul>
<h2>参照</h2>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/exception/rethrow_with_nested.md" target="_blank">編集</a></footer>