<h1>uncaught_exception</h1>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">namespace std {
  // C++03
  bool uncaught_exception() throw();

  // C++11
  bool uncaught_exception() noexcept;
}</span></code></pre>
</p>
<h2>概要</h2>
<p>キャッチされていない例外があるかどうかを判定する。</p>
<h2>戻り値</h2>
<p>例外オブジェクトが生成され、スローされてからキャッチするまでの間にtrueを返す。
また、明示的に<a href="http://cpprefjp.github.io/reference/exception/terminate.html"><code><span style="color: #000">terminate()</span></code></a>を呼び出し、実際に呼び出されるまでの間に<code><span style="color: #000">true</span></code>を返す。</p>
<p>具体的には、tryブロック中で作られたオブジェクトのデストラクタや、スタック巻き戻し(unwind)中のデストラクタ、<a href="http://cpprefjp.github.io/reference/exception/terminate.html"><code><span style="color: #000">terminate()</span></code></a>の場合は生存している全てのオブジェクトのデストラクタで<code><span style="color: #000">true</span></code>になる。</p>
<h2>例外</h2>
<p>投げない</p>
<h2>例</h2>
<p><pre class="codehilite"><code class="language-cpp"><span style="color:#ff0000">uncaught_exception</span>();
    std::cout &lt;&lt; std::boolalpha &lt;&lt; has_uncaught &lt;&lt; std::endl;
  }
};

int main()
{
  try {
    X x;
    throw std::exception();
  }
  catch (std::exception&amp; e) {
    std::cout &lt;&lt; "catch" &lt;&lt; std::endl;
  }
}<span style="color: #000">#include &lt;iostream&gt;
#include &lt;exception&gt;

struct X {
  ~X()
  {
    bool has_uncaught = std::</span></code></pre>
</p>
<h3>出力</h3>
<p><pre><code><span style="color: #000">true
catch
</span></code></pre></p>
<h2>参照</h2>
<p><a href="http://www.gotw.ca/gotw/047.htm" target="_blank">GotW #47 Uncaught Exceptions</a></p>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/exception/uncaught_exception.md" target="_blank">編集</a></footer>