<h1>unexpected</h1>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">namespace std {
  void unexpected();
}</span></code></pre>
</p>
<h2>概要</h2>
<p>例外指定のある関数内で、指定外の例外が発生した時に呼び出される例外ハンドラを直接呼び出す。</p>
<p>この関数を呼び出すと、例外ハンドラが呼ばれ、さらに終了ハンドラが呼び出され、アプリケーションは終了する。ハンドラ内で例外をthrowした場合は、unexpectedを呼び出した地点が、try-catch で処理されていればcatchすることが出来る。</p>
<h2>例</h2>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">#include &lt;stdexcept&gt;
#include &lt;iostream&gt;

void unexpected_handler()
{
  std::cout &lt;&lt; "unexpected handler called" &lt;&lt; std::endl;
}

int main()
{
  std::set_unexpected( unexpected_handler );
  std::unexpected();
}</span></code></pre>
</p>
<h3>出力</h3>
<p><pre><code><span style="color: #000">unexpected handler called
&lt;例外キャッチを行っていないので、アプリケーション自体が終了する&gt;
</span></code></pre></p>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/exception/unexpected.md" target="_blank">編集</a></footer>