<h1>make_ready_at_thread_exit (C++11)</h1>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">void make_ready_at_thread_exit(ArgTypes... args);</span></code></pre>
</p>
<h2>概要</h2>
<p>タスクを実行し、スレッド終了時に準備完了状態にする。
この関数は、タスクの実行と準備完了状態にするタイミングをずらし、準備完了にするのをスレッド終了時まで遅延させたい場合に使用する。</p>
<h2>効果</h2>
<p>メンバ変数として保持している関数オブジェクト<code><span style="color: #000">f</span></code>に対して<a href="http://cpprefjp.github.io/reference/functional/invoke.html"><code><span style="color: #000">INVOKE</span></code></a><code><span style="color: #000">(f, args..., R)</span></code>によって関数呼び出しを行い、その戻り値を<a href="http://cpprefjp.github.io/reference/future/future.html"><code><span style="color: #000">future</span></code></a>との共有状態に格納する。関数<code><span style="color: #000">f</span></code>の内部で例外が送出された場合は、共有状態に送出された例外が格納される。
現在のスレッドが終了し、スレッドローカル記憶域を持つ全てのオブジェクトを破棄したあと、準備完了状態(<a href="http://cpprefjp.github.io/reference/future/future_status.html"><code><span style="color: #000">future_status::ready</span></code></a>)にする。</p>
<h2>戻り値</h2>
<p>なし</p>
<h2>例外</h2>
<p>この関数は、以下のerror conditionを持つ<a href="http://cpprefjp.github.io/reference/future/future_error.html"><code><span style="color: #000">future_error</span></code></a>例外オブジェクトを送出する可能性がある：</p>
<ul>
<li><a href="http://cpprefjp.github.io/reference/future/future_errc.html"><code><span style="color: #000">promise_already_satisfied</span></code></a> ： 格納されたタスクがすでに実行された</li>
<li><a href="http://cpprefjp.github.io/reference/future/future_errc.html"><code><span style="color: #000">no_state</span></code></a>： <code><span style="color: #000">*this</span></code>が共有状態を持っていない(<code><span style="color: #000">packaged_task</span></code>オブジェクトがムーブされると起こりうる)</li>
</ul>
<h2>例</h2>
<p><pre class="codehilite"><code class="language-cpp"><a href="http://connect.microsoft.com/VisualStudio/feedback/details/737812" target="_blank">http://connect.microsoft.com/VisualStudio/feedback/details/737812</a>
void calc(std::packaged_task&lt;int(int, int)&gt;&amp; task)
{
  // 現在のスレッド終了時に準備完了状態にする
  task.make_ready_at_thread_exit(2, 3);
}

int main()
{
  std::packaged_task&lt;int(int, int)&gt; task(plus_task);
  std::future&lt;int&gt; f = task.get_future();

  std::thread t(calc, std::ref(task));
  t.detach();

  // タスクの結果を取得
  int result = f.get();
  std::cout &lt;&lt; result &lt;&lt; std::endl;
}<span style="color: #000">#include &lt;iostream&gt;
#include &lt;future&gt;
#include &lt;thread&gt;
#include &lt;functional&gt;

int plus_task(int a, int b)
{
  return a + b;
}

// packaged_taskを左辺値参照にしているのはVisual C++ 2012のバグのため
// </span></code></pre>
</p>
<h3>出力</h3>
<p><pre><code><span style="color: #000">5
</span></code></pre></p>
<h2>バージョン</h2>
<h3>言語</h3>
<ul>
<li>C++11</li>
</ul>
<h3>処理系</h3>
<ul>
<li><a href="http://cpprefjp.github.io/implementation.html#clang">Clang</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC</a>: </li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC, C++0x mode</a>: </li>
<li><a href="http://cpprefjp.github.io/implementation.html#icc">ICC</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#visual_cpp">Visual C++</a>: 11.0</li>
</ul>
<h2>参照</h2>
<p><a href="http://cpprefjp.github.io/article/at_thread_exit.html">_at_thread_exit系の関数が存在している理由</a></p>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/future/packaged_task/make_ready_at_thread_exit.md" target="_blank">編集</a></footer>