<h1>exception</h1>
<p><code><span style="color: #000">&lt;exception&gt;</span></code>ヘッダでは、C++プログラムでの例外の扱いに関連した、いくつかのクラスと関数を定義する。</p>
<table border="1" bordercolor="#888" style="border-collapse:collapse">
<thead>
<tr>
<th>名前</th>
<th>説明</th>
<th>対応バージョン</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/exception.html"><code><span style="color: #000">exception</span></code></a></td>
<td>標準例外の基本クラス(class)</td>
<td></td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/bad_exception.html"><code><span style="color: #000">bad_exception</span></code></a></td>
<td>関数で例外の型を制限し、指定外の方が送出された場合に発生させる(class)</td>
<td></td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/nested_exception.html"><code><span style="color: #000">nested_exception</span></code></a></td>
<td>例外構造をネストさせる場合に利用する例外クラス(class)</td>
<td>C++11</td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/set_unexpected.html"><code><span style="color: #000">set_unexpected</span></code></a></td>
<td>予想外の例外が発生した場合の処理を行う関数を設定する(function)</td>
<td></td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/get_unexpected.html"><code><span style="color: #000">get_unexpected</span></code></a></td>
<td>予想外の例外が発生した場合の処理を行う関数を取得する(function)</td>
<td>C++11</td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/unexpected.html"><code><span style="color: #000">unexpected</span></code></a></td>
<td>予想外の例外が発生した場合の処理を呼び出す(function)</td>
<td></td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/set_terminate.html"><code><span style="color: #000">set_terminate</span></code></a></td>
<td>例外が処理されなかった場合の処理を行う関数を設定する(function)</td>
<td></td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/get_terminate.html"><code><span style="color: #000">get_terminate</span></code></a></td>
<td>例外が処理されなかった場合の処理を行う関数を取得する(function)</td>
<td></td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/terminate.html"><code><span style="color: #000">terminate</span></code></a></td>
<td>例外が処理されなかった場合の処理を行う関数を呼び出す(function)</td>
<td></td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/uncaught_exception.html"><code><span style="color: #000">uncaught_exception</span></code></a></td>
<td>例外処理中かを判別する(function)</td>
<td></td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/exception_ptr.html"><code><span style="color: #000">exception_ptr</span></code></a></td>
<td>例外格納用ポインタ(typedef)</td>
<td>C++11</td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/current_exception.html"><code><span style="color: #000">current_exception</span></code></a></td>
<td>現在処理中の例外オブジェクトを指す例外ポインタを取得する(function)</td>
<td>C++11</td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/rethrow_exception.html"><code><span style="color: #000">rethrow_exception</span></code></a></td>
<td>例外ポインタが指す例外を送出する(function)</td>
<td>C++11</td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/make_exception_ptr.html"><code><span style="color: #000">make_exception_ptr</span></code></a></td>
<td>例外ポインタを作成する(function)</td>
<td>C++11</td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/throw_with_nested.html"><code><span style="color: #000">throw_with_nested</span></code></a></td>
<td>現在の例外を入れ子にした例外を送出する(function)</td>
<td>C++11</td>
</tr>
<tr>
<td><a href="http://cpprefjp.github.io/reference/exception/rethrow_with_nested.html"><code><span style="color: #000">rethrow_if_nested</span></code></a></td>
<td>入れ子になった例外が存在する場合に、入れ子になった例外を送出する(function)</td>
<td>C++11</td>
</tr>
</tbody>
</table>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/exception.md" target="_blank">編集</a></footer>